/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dsl.talk

import java.util.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

}

fun String.toUUID() = UUID.fromString(this)

val String.uuid get() = UUID.fromString(this)

fun main() {
    val uuid = "e49c499b-d9d0-46fb-8b35-a3d3ecf89569".toUUID()
    val uuid2 = "e49c499b-d9d0-46fb-8b35-a3d3ecf89569".uuid

    val s1 = (1 .. 10).joinToString("/", transform = { i -> "($i)" })
    val s2 = (1 .. 10).joinToString("/") { "<$it>" }

    val sum: Int.(Int) -> Int = { other -> this + other }

    var x = 10.sum(20)

    data class Counter(var n: Int) {
        fun doubleIt() { n *=2 }
    }

    val inc: Counter.(Int) -> Unit = {
        n += 10
        doubleIt()
    }

    val y = Counter(0)

    y.inc(10)

    fun withCounter(counter: Counter, f: Counter.() -> Unit) {
        counter.apply(f)
    }

    val y = Counter(0)

    withCounter(y) {
        n += 10
        doubleIt()
    }

    // y.n = 20




    y.inc(10)


    infix fun String.repeated (n: Int) =
            this.repeat(n)

    val string = "foo" repeated 10

    operator fun String.times(n: Int) =
            this.repeated(n)

    val s = "foo" * 10
    "foo".times(10)

    operator fun StringBuilder.invoke(body: StringBuilder.() -> Unit) {
        this.apply(body)
    }

    val aString = StringBuilder()

    aString {
        append("Hello, ")
        append("World!")
    }

    println(aString)
    println(App().greeting)
}
